// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using System;

namespace TradeHelper.EntityModel.Migrations
{
    [DbContext(typeof(TradeHelperContext))]
    [Migration("20180505210140_UpdateDecimalPrecision")]
    partial class UpdateDecimalPrecision
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TradeHelper.EntityModel.Entities.TradeInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal>("Amount");

                    b.Property<decimal?>("BuyPrice")
                        .HasColumnType("decimal(10, 4)");

                    b.Property<decimal?>("CellPrice")
                        .HasColumnType("decimal(10, 4)");

                    b.Property<DateTime?>("CloseDate");

                    b.Property<string>("PairCode");

                    b.Property<int>("PositionId");

                    b.Property<DateTime?>("StartDate");

                    b.Property<int>("StatusId");

                    b.HasKey("Id");

                    b.ToTable("TradeInfo");
                });
#pragma warning restore 612, 618
        }
    }
}
