//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TradeInfo
    {
        public System.Guid Id { get; set; }
        public string PairCode { get; set; }
        public decimal Amount { get; set; }
        public Nullable<decimal> BuyPrice { get; set; }
        public Nullable<decimal> CellPrice { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> CloseDate { get; set; }
        public int StatusId { get; set; }
        public int PositionId { get; set; }
    }
}
